# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'Better Science Through Superior Software'
description:      ''
url:              http://www.camillescott.org/dib-lab
baseurl:          /dib-lab

author:
  name:           'Camille Scott'
  url:            https://twitter.com/camille_codon

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
    repo:           https://github.com/camillescott/dib-lab
